#ifndef RISCV_VENTUS_VTAS_ABI_GENERATED_H
#define RISCV_VENTUS_VTAS_ABI_GENERATED_H
// Generated by tools/rtcore_abi.py from mesa/src/ventus/common/ventus_rt_bvh.h.
// Do not edit: update the Mesa VTAS ABI header and regenerate.
// Fixed VTAS binary-layout constants for namespace ventus_rt.

constexpr uint32_t as_magic = 1396790358;
constexpr uint32_t as_version = 2;
constexpr uint32_t as_header_size = 128;
constexpr uint32_t as_box4_node_size = 128;
constexpr uint32_t as_triangle_node_size = 64;
constexpr uint32_t as_aabb_node_size = 64;
constexpr uint32_t as_instance_node_size = 128;
constexpr uint32_t invalid_node_ref = 0xffffffffu;
constexpr uint32_t node_ref_type_mask = 7;
constexpr uint32_t node_ref_offset_mask = 0xfffffff8u;
constexpr uint32_t as_type_blas = 1;
constexpr uint32_t as_type_tlas = 2;
constexpr uint32_t node_invalid = 0;
constexpr uint32_t node_box4 = 1;
constexpr uint32_t node_triangle = 2;
constexpr uint32_t node_instance = 3;
constexpr uint32_t node_aabb = 4;
constexpr uint32_t as_header_magic = 0;
constexpr uint32_t as_header_version = 4;
constexpr uint32_t as_header_header_size = 6;
constexpr uint32_t as_header_type = 8;
constexpr uint32_t as_header_flags = 12;
constexpr uint32_t as_header_root_node_offset = 16;
constexpr uint32_t as_header_root_node_ref = 16;
constexpr uint32_t as_header_node_count = 20;
constexpr uint32_t as_header_node_region_offset = 24;
constexpr uint32_t as_header_node_region_size = 28;
constexpr uint32_t as_header_primitive_region_offset = 32;
constexpr uint32_t as_header_primitive_count = 36;
constexpr uint32_t as_header_instance_region_offset = 40;
constexpr uint32_t as_header_instance_count = 44;
constexpr uint32_t as_header_root_aabb_min_x = 48;
constexpr uint32_t as_header_root_aabb_min_y = 52;
constexpr uint32_t as_header_root_aabb_min_z = 56;
constexpr uint32_t as_header_root_aabb_max_x = 60;
constexpr uint32_t as_header_root_aabb_max_y = 64;
constexpr uint32_t as_header_root_aabb_max_z = 68;
constexpr uint32_t box4_child_ref = 0;
constexpr uint32_t box4_min_x = 16;
constexpr uint32_t box4_min_y = 32;
constexpr uint32_t box4_min_z = 48;
constexpr uint32_t box4_max_x = 64;
constexpr uint32_t box4_max_y = 80;
constexpr uint32_t box4_max_z = 96;
constexpr uint32_t box4_child_flags = 112;
constexpr uint32_t triangle_v0 = 0;
constexpr uint32_t triangle_v1 = 12;
constexpr uint32_t triangle_v2 = 24;
constexpr uint32_t triangle_primitive_id = 36;
constexpr uint32_t triangle_geometry_id = 40;
constexpr uint32_t triangle_sbt_record_offset = 44;
constexpr uint32_t triangle_flags = 48;
constexpr uint32_t triangle_instance_id = 52;
constexpr uint32_t triangle_primitive_addr_lo = 56;
constexpr uint32_t triangle_primitive_addr_hi = 60;
constexpr uint32_t aabb_min = 0;
constexpr uint32_t aabb_max = 12;
constexpr uint32_t aabb_primitive_id = 24;
constexpr uint32_t aabb_geometry_id = 28;
constexpr uint32_t aabb_sbt_record_offset = 32;
constexpr uint32_t aabb_hit_kind = 36;
constexpr uint32_t aabb_flags = 40;
constexpr uint32_t aabb_primitive_addr_lo = 48;
constexpr uint32_t aabb_primitive_addr_hi = 52;
constexpr uint32_t aabb_instance_addr_lo = 56;
constexpr uint32_t aabb_instance_addr_hi = 60;
constexpr uint32_t instance_blas_addr_lo = 0;
constexpr uint32_t instance_blas_addr_hi = 4;
constexpr uint32_t instance_custom_index = 8;
constexpr uint32_t instance_mask = 12;
constexpr uint32_t instance_sbt_record_offset = 16;
constexpr uint32_t instance_flags = 20;
constexpr uint32_t instance_instance_id = 24;
constexpr uint32_t instance_reserved = 28;
constexpr uint32_t instance_object_to_world = 32;
constexpr uint32_t instance_world_to_object = 80;

#endif
