#ifndef RISCV_VENTUS_RT_ABI_GENERATED_H
#define RISCV_VENTUS_RT_ABI_GENERATED_H
// Generated by tools/rtcore_abi.py from mesa/src/ventus/compiler/vt_rt_abi.h.
// Do not edit: update the Mesa ABI header and regenerate.
// Fixed PDS-header constants for namespace ventus_rt.

constexpr reg_t abi_version = 5;
constexpr reg_t abi_word_bytes = 4;
constexpr reg_t abi_alignment_bytes = 16;
constexpr reg_t abi_ray_state_base_bytes = 0;
constexpr reg_t abi_ray_state_size_bytes = 92;
constexpr reg_t abi_cps_header_base_bytes = 96;
constexpr reg_t abi_cps_header_size_bytes = 16;
constexpr reg_t abi_control_base_bytes = 112;
constexpr reg_t abi_control_size_bytes = 4;
constexpr reg_t abi_candidate_hit_record_base_bytes = 116;
constexpr reg_t abi_candidate_hit_record_size_bytes = 72;
constexpr reg_t abi_committed_hit_record_base_bytes = 196;
constexpr reg_t abi_committed_hit_record_size_bytes = 72;
constexpr reg_t abi_hit_attrib_base_bytes = 276;
constexpr reg_t abi_shader_region_base_bytes = 276;
constexpr reg_t abi_fixed_header_size_bytes = 276;
constexpr reg_t slot_status = 0;
constexpr reg_t slot_accel_lo = 1;
constexpr reg_t slot_accel_hi = 2;
constexpr reg_t slot_flags = 3;
constexpr reg_t slot_cull_mask = 4;
constexpr reg_t slot_sbt_offset = 5;
constexpr reg_t slot_sbt_stride = 6;
constexpr reg_t slot_miss_index = 7;
constexpr reg_t slot_origin_x = 8;
constexpr reg_t slot_origin_y = 9;
constexpr reg_t slot_origin_z = 10;
constexpr reg_t slot_tmin = 11;
constexpr reg_t slot_direction_x = 12;
constexpr reg_t slot_direction_y = 13;
constexpr reg_t slot_direction_z = 14;
constexpr reg_t slot_tmax = 15;
constexpr reg_t slot_payload_ptr_lo = 16;
constexpr reg_t slot_payload_ptr_hi = 17;
constexpr reg_t slot_hit_t = 18;
constexpr reg_t slot_sbt_index = 19;
constexpr reg_t slot_launch_id_x = 20;
constexpr reg_t slot_launch_id_y = 21;
constexpr reg_t slot_launch_id_z = 22;
constexpr reg_t slot_word_count = 23;
constexpr reg_t slot_status_idle = 0;
constexpr reg_t slot_status_trace_request = 1;
constexpr reg_t slot_status_terminated = 2;
constexpr reg_t traversal_complete_miss = 0;
constexpr reg_t traversal_complete_hit = 1;
constexpr reg_t traversal_candidate_non_opaque_triangle = 2;
constexpr reg_t traversal_candidate_procedural_aabb = 3;
constexpr reg_t traversal_terminated = 4;
constexpr reg_t hit_record_status = 0;
constexpr reg_t hit_record_hit_t = 1;
constexpr reg_t hit_record_sbt_index = 2;
constexpr reg_t hit_record_shader_record_ptr_lo = 3;
constexpr reg_t hit_record_shader_record_ptr_hi = 4;
constexpr reg_t hit_record_primitive_id = 5;
constexpr reg_t hit_record_instance_id = 6;
constexpr reg_t hit_record_geometry_id = 7;
constexpr reg_t hit_record_hit_kind = 8;
constexpr reg_t hit_record_barycentrics_x = 9;
constexpr reg_t hit_record_barycentrics_y = 10;
constexpr reg_t hit_record_primitive_addr_lo = 11;
constexpr reg_t hit_record_primitive_addr_hi = 12;
constexpr reg_t hit_record_instance_addr_lo = 13;
constexpr reg_t hit_record_instance_addr_hi = 14;
constexpr reg_t hit_record_front_face = 15;
constexpr reg_t hit_record_opaque = 16;
constexpr reg_t hit_record_need_software_opacity_test = 17;
constexpr reg_t hit_record_instance_sbt_record_offset = 18;
constexpr reg_t hit_record_word_count = 19;
constexpr reg_t hit_record_status_invalid = 0;
constexpr reg_t hit_record_status_valid = 1;
constexpr reg_t control_callback_decision = 0;
constexpr reg_t control_word_count = 1;
constexpr reg_t callback_pending = 0;
constexpr reg_t callback_accept = 1;
constexpr reg_t callback_ignore = 2;
constexpr reg_t callback_terminate = 3;
constexpr reg_t cps_frame_base = 0;
constexpr reg_t cps_active_level = 1;
constexpr reg_t cps_fragment_id = 2;
constexpr reg_t cps_flags = 3;
constexpr reg_t cps_header_word_count = 4;

constexpr reg_t abi_payload_base_bytes_for_hit_attrib_size(reg_t hit_attrib_size_bytes)
{
  return (abi_hit_attrib_base_bytes + 2 * (hit_attrib_size_bytes));
}

#endif
