#ifndef RISCV_VENTUS_RT_ABI_GENERATED_H
#define RISCV_VENTUS_RT_ABI_GENERATED_H
// Generated by tools/rtcore_abi.py from mesa/src/ventus/compiler/vt_rt_abi.h.
// Do not edit: update the Mesa ABI header and regenerate.
// Fixed RT Local header constants for namespace ventus_rt.

constexpr reg_t abi_version = 11;
constexpr reg_t abi_word_bytes = 4;
constexpr reg_t abi_alignment_bytes = 16;
constexpr reg_t trace_meta0_flags_shift = 0;
constexpr reg_t trace_meta0_flags_bits = 8;
constexpr reg_t trace_meta0_cull_mask_shift = 8;
constexpr reg_t trace_meta0_cull_mask_bits = 8;
constexpr reg_t trace_meta0_sbt_offset_shift = 16;
constexpr reg_t trace_meta0_sbt_offset_bits = 4;
constexpr reg_t trace_meta0_sbt_stride_shift = 20;
constexpr reg_t trace_meta0_sbt_stride_bits = 4;
constexpr reg_t trace_meta1_miss_index_shift = 0;
constexpr reg_t trace_meta1_miss_index_bits = 16;
constexpr reg_t trace_meta1_active_level_shift = 16;
constexpr reg_t trace_meta1_active_level_bits = 8;
constexpr reg_t trace_meta1_max_recursion_depth = 256;
constexpr reg_t hit_record_meta0_valid_shift = 0;
constexpr reg_t hit_record_meta0_status_shift = 1;
constexpr reg_t hit_record_meta0_status_bits = 3;
constexpr reg_t hit_record_meta0_front_face_shift = 4;
constexpr reg_t hit_record_meta0_opaque_shift = 5;
constexpr reg_t hit_record_meta0_need_software_opacity_test_shift = 6;
constexpr reg_t hit_record_meta0_instance_custom_index_shift = 7;
constexpr reg_t hit_record_meta0_instance_custom_index_bits = 24;
constexpr reg_t hit_record_meta1_instance_sbt_record_offset_shift = 0;
constexpr reg_t hit_record_meta1_instance_sbt_record_offset_bits = 24;
constexpr reg_t local_ray_state_base_bytes = 0;
constexpr reg_t local_ray_state_size_bytes = 72;
constexpr reg_t local_control_base_bytes = 72;
constexpr reg_t local_control_size_bytes = 4;
constexpr reg_t local_candidate_hit_record_base_bytes = 76;
constexpr reg_t local_candidate_hit_record_size_bytes = 36;
constexpr reg_t local_committed_hit_record_base_bytes = 112;
constexpr reg_t local_committed_hit_record_size_bytes = 36;
constexpr reg_t local_field_major_fixed_header_word_count = 37;
constexpr reg_t local_header_size_bytes = 148;
constexpr reg_t pds_candidate_hit_attrib_base_bytes = 0;
constexpr reg_t slot_status = 0;
constexpr reg_t slot_accel_lo = 1;
constexpr reg_t slot_accel_hi = 2;
constexpr reg_t slot_trace_meta0 = 3;
constexpr reg_t slot_trace_meta1 = 4;
constexpr reg_t slot_origin_x = 5;
constexpr reg_t slot_origin_y = 6;
constexpr reg_t slot_origin_z = 7;
constexpr reg_t slot_tmin = 8;
constexpr reg_t slot_direction_x = 9;
constexpr reg_t slot_direction_y = 10;
constexpr reg_t slot_direction_z = 11;
constexpr reg_t slot_tmax = 12;
constexpr reg_t slot_payload_ptr_lo = 13;
constexpr reg_t slot_payload_ptr_hi = 14;
constexpr reg_t slot_launch_id_x = 15;
constexpr reg_t slot_launch_id_y = 16;
constexpr reg_t slot_launch_id_z = 17;
constexpr reg_t slot_word_count = 18;
constexpr reg_t slot_status_idle = 0;
constexpr reg_t slot_status_trace_request = 1;
constexpr reg_t slot_status_terminated = 2;
constexpr reg_t traversal_complete_miss = 0;
constexpr reg_t traversal_complete_hit = 1;
constexpr reg_t traversal_candidate_non_opaque_triangle = 2;
constexpr reg_t traversal_candidate_procedural_aabb = 3;
constexpr reg_t traversal_terminated = 4;
constexpr reg_t hit_record_meta0 = 0;
constexpr reg_t hit_record_meta1 = 1;
constexpr reg_t hit_record_hit_t = 2;
constexpr reg_t hit_record_barycentrics_x = 3;
constexpr reg_t hit_record_barycentrics_y = 4;
constexpr reg_t hit_record_primitive_id = 5;
constexpr reg_t hit_record_instance_id = 6;
constexpr reg_t hit_record_geometry_id = 7;
constexpr reg_t hit_record_hit_kind = 8;
constexpr reg_t hit_record_word_count = 9;
constexpr reg_t hit_record_status_invalid = 0;
constexpr reg_t hit_record_status_valid = 1;
constexpr reg_t control_callback_decision = 0;
constexpr reg_t control_word_count = 1;
constexpr reg_t callback_pending = 0;
constexpr reg_t callback_accept = 1;
constexpr reg_t callback_ignore = 2;
constexpr reg_t callback_terminate = 3;

constexpr reg_t pds_payload_base_bytes(reg_t hit_attrib_size_bytes)
{
  return (2 * (hit_attrib_size_bytes));
}

#endif
